### ISSUE TITLE
Retail Build Fails to Boot-up on 17763 Windows Version - Brief Windows Screen & then blue screen appears

### ISSUE THREAD

**Issue by majidshaffi** [ms-iot/iot-adk-addonkit#306]
Hi @parameshbabu,

I am trying to build a retail image on 17763 windows version along with packaging our custom applications and scripts in it. The image builds fine for both test and retail, but for retail windows boot-up there is a brief windows screen and then blue screen appears. Finally after 2 minutes the screen goes dark and raspberry pi shuts down.

I have read couple of similar issues here and double checked that the BSP's are properly signed and built. We are using a standard code sign certificate issued from Go Daddy and built retail images many times using the same cert and process on 16299.64 and 17134.1 windows versions. However, for 17763 version of windows, I am unable to identify the problem.

I have done a lot of testing around it and also built image without any customization and custom apps but the image still does not boot-up.

The details of the environment are:

**ADK_VERSION : 10.0.17763.1
IOTCORE_VER : 10.0.17763.107
BSP_VERSION : 10.0.0.0
ADDONKITVER : 6.0.190116.1218
HostOS Info : Microsoft Windows 10 Pro - 10.0.17134 - en-US**

Moreover, just to be on the safe side I also signed the .sys and .dll files within the BSP folder as well apart from just signing the .cab files in build pkg folder. The screenshot is attached below and all of the 12 BSP drivers are signed like this.

![image](https://user-images.githubusercontent.com/40349849/53320278-e679f600-3920-11e9-9b73-dddb5f15fb68.png)

![image](https://user-images.githubusercontent.com/40349849/53320328-0c06ff80-3921-11e9-8786-70e97e54c2f1.png)

Your help in this regard would be highly appreciable.

Thanks,

Majid Shaffi

**Comment by parameshbabu** [comment]
Hi,
when you signed the .sys / .dll files within the bsp folder, did you use the Redo-IoTCabSignature(re-signcabs)? There are a couple of files that should not be touched (hal drivers).

**Comment by majidshaffi** [comment]
Hi @parameshbabu ,

Yes I used Redo-IoTCabSignature for signing the .sys and .dll files within the BSP folder. Also, I used Redo-IoTCabSignature to sign all the .cab files in build/pkg folder as well.

I cannot see any hal drivers in the BSP folder, also when using the Redo-IoTCabSignature I am specifying *.dll and *.sys to sign only the specified files.

**Comment by majidshaffi** [comment]
@parameshbabu Any update on the above issue? We are close on releasing our app with retail build on 17763. Would highly appreciate your help in this.

Thanks,

Majid Shaffi

**Comment by parameshbabu** [comment]
@majidshaffi can you try a sample product build with your certificate for retail, to ensure that we dont have any other issues in there? The info above is insufficient to investigate this and it will help if you can confirm the ability to build our samples with your retail certificate. (RpiRecovery)

**Comment by majidshaffi** [comment]
@parameshbabu  Our issue is fixed and it is apparently the BSP's were not signed properly when imported into the work-space so instead I have to used Sign.cmd to initially sign all BSP's and then import them into the work-space.
You can mark this issue as closed and thanks for all the help.

**Comment by GBelchior** [comment]
@majidshaffi I'm still having this issue. I tried to sign the BSPs with my certificate before importing them into the workspace, but the retail version is still not booting. Can you provide more details on how you managed to make it work? Thanks in advance.

**Comment by majidshaffi** [comment]
@GBelchior  Unzip the BSP package and use the sign.cmd utility inside the iot_toolkit to sign all *.dll's and *.sys files individually. After that use the import bsp command to import the BSP packages into your workspace. The issue is that I was importing the BSP.zip into the workspace so all the dll's and sys files were not able to be signed by our code signing certificate.
Let me know if that works for you.

**Comment by parameshbabu** [comment]
You could just do "signbinaries bsp folder" to sign the binaries in your workspace directly.
